# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='month_year',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
