# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_work_month_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='user',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
